import type { GetStaticProps, NextPage } from 'next'
import Head from 'next/head'
import { useDispatch } from 'react-redux'
import { Step } from '@/@types/types'
import axios from 'axios'
import { Footer, SkillTables } from '@/components'
import { setSteps } from '@/slice/stepSlice'
import styled from 'styled-components'
import variables from '../styles/variables.module.scss'
// import {
//   SkillTables
// } from 'portfolio/src/components'

// SSG処理
export const getStaticProps: GetStaticProps = async () => {
  const req = await axios.get('http://localhost:3000/api/steps')
  const steps: Step[] = req.data
  return { props: { steps } }
}

type Props = {
  steps: Step[]
}

interface TextProps {
  color?: string;
}

const _Container = styled.div`
  padding: 0;
`

const _Text = styled.p<TextProps>`
  font-size: 30px;
  color: ${(p) => p.color};
`

const Home: NextPage<Props> = ({ steps }) => {
  // src/store/store.ts の counter を指している。
  const dispatch = useDispatch()
  dispatch(setSteps(steps))

  return (
    <_Container>
      <Head>
        <title>My Portfolio_Redux</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <p style={{color: variables.primaryColor }}>aaaaaa</p>
      <_Text>My Portfolio_Redux</_Text>
      <SkillTables></SkillTables>
      <Footer></Footer>
    </_Container>
  )
}

export default Home
